name: arogya_direct
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter:
  geolocator:
  firebase_core: 
  cloud_firestore : ^4.8.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  
flutter:
  uses-material-design: true


  assets:
     - assets/images/

